<?php
function theme_name_scripts(){
wp_enqueue_style( 'main', get_template_directory_uri() . '/css/style.css');
wp_enqueue_style( 'buttons', get_template_directory_uri() . '/css/buttons/buttons.css');
wp_enqueue_style( 'font', get_template_directory_uri() . '/css/font-awesome.min.css');
wp_enqueue_style( 'bootstrap', get_template_directory_uri() . '/css/bootstrap.min.css');
wp_enqueue_style( 'jslidder', get_template_directory_uri() . '/css/jslider.css');
wp_enqueue_style( 'settings', get_template_directory_uri() . '/css/settings.css');
wp_enqueue_style( 'fancybox', get_template_directory_uri() . '/css/jquery.fancybox.css');
wp_enqueue_style( 'animate', get_template_directory_uri() . '/css/animate.css');
wp_enqueue_style( 'video', get_template_directory_uri() . '/css/video-js.min.css');
wp_enqueue_style( 'morris', get_template_directory_uri() . '/css/morris.css');
wp_enqueue_style( 'royalslider', get_template_directory_uri() . '/css/royalslider/royalslider.css');
wp_enqueue_style( 'minimal-white', get_template_directory_uri() . '/css/royalslider/skins/minimal-white/rs-minimal-white.css');
wp_enqueue_style( 'layerslider', get_template_directory_uri() . '/css/layerslider/layerslider.css');
wp_enqueue_style( 'ladda', get_template_directory_uri() . '/css/ladda.min.css');
wp_enqueue_style( 'datepicker', get_template_directory_uri() . '/css/datepicker.css');
wp_enqueue_style( 'scrollbar', get_template_directory_uri() . '/css/jquery.scrollbar.css');
wp_enqueue_style( 'responsive', get_template_directory_uri() . '/css/responsive.css');
wp_enqueue_style( 'pages', get_template_directory_uri() . '/css/customizer/pages.css');
wp_enqueue_style( 'home-pages', get_template_directory_uri() . '/css/customizer/home-pages-customizer.css');
wp_enqueue_style( 'ie', get_template_directory_uri() . '/css/ie/ie.css');


wp_enqueue_script("jquery");
wp_enqueue_script( 'tabuler', get_template_directory_uri() . '/js/jquery.tubular.1.0.js');
wp_enqueue_script( 'SmoothScroll', get_template_directory_uri() . '/js/SmoothScroll.js');
wp_enqueue_script( 'country', get_template_directory_uri() . '/js/country.js');
wp_enqueue_script( 'spin', get_template_directory_uri() . '/js/spin.min.js');
wp_enqueue_script( 'ladda', get_template_directory_uri() . '/js/ladda.min.js');
wp_enqueue_script( 'masonry', get_template_directory_uri() . '/js/masonry.pkgd.min.js');
wp_enqueue_script( 'morris', get_template_directory_uri() . '/js/morris.min.js');
wp_enqueue_script( 'raphael', get_template_directory_uri() . '/js/raphael.min.js');
wp_enqueue_script( 'video', get_template_directory_uri() . '/js/video.js');
wp_enqueue_script( 'pixatic', get_template_directory_uri() . '/js/pixastic.custom.js');
wp_enqueue_script( 'livicons', get_template_directory_uri() . '/js/livicons-1.3.min.js');
wp_enqueue_script( 'greensock', get_template_directory_uri() . '/js/layerslider/greensock.js');
wp_enqueue_script( 'transitions', get_template_directory_uri() . '/js/layerslider/layerslider.transitions.js');
wp_enqueue_script( 'kreaturamedia', get_template_directory_uri() . '/js/layerslider/layerslider.kreaturamedia.jquery.js');
wp_enqueue_script( 'plugins', get_template_directory_uri() . '/js/revolution/jquery.themepunch.plugins.min.js');
wp_enqueue_script( 'themepunch', get_template_directory_uri() . '/js/revolution/jquery.themepunch.revolution.min.js');
wp_enqueue_script( 'validator', get_template_directory_uri() . '/js/bootstrapValidator.min.js');
wp_enqueue_script( 'datepicker', get_template_directory_uri() . '/js/bootstrap-datepicker.js');
wp_enqueue_script( 'jplayer', get_template_directory_uri() . '/js/jplayer/jquery.jplayer.min.js');
wp_enqueue_script( 'playlist', get_template_directory_uri() . '/js/jplayer/jplayer.playlist.min.js');
wp_enqueue_script( 'main', get_template_directory_uri() . '/js/main.js');
wp_enqueue_script( 'scrollbar', get_template_directory_uri() . '/js/jquery.scrollbar.min.js');
wp_enqueue_script( 'royalslider', get_template_directory_uri() . '/js/jquery.royalslider.min.js');
wp_enqueue_script( 'selectBox', get_template_directory_uri() . '/js/jquery.selectBox.min.js');
wp_enqueue_script( 'steller', get_template_directory_uri() . '/js/jquery.stellar.min.js');
wp_enqueue_script( 'knob', get_template_directory_uri() . '/js/jquery.knob.js');
wp_enqueue_script( 'pkgd', get_template_directory_uri() . '/js/isotope.pkgd.min.js');
wp_enqueue_script( 'fancybox', get_template_directory_uri() . '/js/jquery.fancybox.pack.js');
wp_enqueue_script( 'easing', get_template_directory_uri() . '/js/jquery.easing.1.3.js');
wp_enqueue_script( 'easypiechart', get_template_directory_uri() . '/js/jquery.easypiechart.min.js');
wp_enqueue_script( 'sparkline', get_template_directory_uri() . '/js/jquery.sparkline.min.js');
wp_enqueue_script( 'appear', get_template_directory_uri() . '/js/jquery.appear.js');
wp_enqueue_script( 'imagesloaded', get_template_directory_uri() . '/js/jquery.imagesloaded.min.js');
wp_enqueue_script( 'elevatezoom', get_template_directory_uri() . '/js/jquery.elevateZoom-3.0.8.min.js');
wp_enqueue_script( 'touchSwipe', get_template_directory_uri() . '/js/jquery.touchSwipe.min.js');
wp_enqueue_script( 'packed', get_template_directory_uri() . '/js/jquery.carouFredSel-6.2.1-packed.js');
wp_enqueue_script( 'slider', get_template_directory_uri() . '/js/price-regulator/jquery.slider.js');
wp_enqueue_script( 'draggable', get_template_directory_uri() . '/js/price-regulator/draggable-0.1.js');
wp_enqueue_script( 'dependClass', get_template_directory_uri() . '/js/price-regulator/jquery.dependClass-0.1.js');
wp_enqueue_script( 'tmpl', get_template_directory_uri() . '/js/price-regulator/tmpl.js');
wp_enqueue_script( 'numberformatter', get_template_directory_uri() . '/js/price-regulator/jquery.numberformatter-1.2.3.js');
wp_enqueue_script( 'jshashtable', get_template_directory_uri() . '/js/price-regulator/jshashtable-2.1_src.js');
wp_enqueue_script( 'bootstrap', get_template_directory_uri() . '/js/bootstrap.min.js');
}
add_action( 'wp_enqueue_scripts', 'theme_name_scripts' );
